declare const styles: {
  readonly adjacent: string;
  readonly adjacentLabel: string;
  readonly adjacentLink: string;
  readonly adjacentOlder: string;
  readonly adjacentTitle: string;
  readonly article: string;
  readonly articleBody: string;
  readonly articleDeck: string;
  readonly articleHeader: string;
  readonly articleTitle: string;
  readonly featureCover: string;
  readonly heroImage: string;
  readonly metaLine: string;
  readonly tagLink: string;
  readonly tagRow: string;
  readonly tocItemH2: string;
  readonly tocItemH3: string;
  readonly tocList: string;
  readonly tocPill: string;
  readonly tocPillIcon: string;
  readonly tocPillPanel: string;
  readonly tocPillSummary: string;
  readonly tocRail: string;
  readonly tocRailLabel: string;
};
export default styles;
