declare const styles: {
  readonly brand: string;
  readonly brandHeading: string;
  readonly content: string;
  readonly footer: string;
  readonly footerLink: string;
  readonly iconLink: string;
  readonly intro: string;
  readonly mastNav: string;
  readonly masthead: string;
  readonly navLink: string;
  readonly page: string;
  readonly push: string;
  readonly search: string;
  readonly searchField: string;
  readonly searchInput: string;
  readonly shell: string;
  readonly visuallyHidden: string;
};
export default styles;
