/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaAssetsAssetIdRouteImport } from './routes/media-assets/$assetId'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as BlogSiteSlugIndexRouteImport } from './routes/blog/$siteSlug/index'
import { Route as BlogSiteSlugLlmsDottxtRouteImport } from './routes/blog/$siteSlug/llms[.]txt'
import { Route as BlogSiteSlugPostSlugRouteImport } from './routes/blog/$siteSlug/$postSlug'
import { Route as ApiOnboardingEnsureRouteImport } from './routes/api/onboarding/ensure'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaAssetsAssetIdRoute = MediaAssetsAssetIdRouteImport.update({
  id: '/media-assets/$assetId',
  path: '/media-assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSiteSlugIndexRoute = BlogSiteSlugIndexRouteImport.update({
  id: '/blog/$siteSlug/',
  path: '/blog/$siteSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSiteSlugLlmsDottxtRoute = BlogSiteSlugLlmsDottxtRouteImport.update({
  id: '/blog/$siteSlug/llms.txt',
  path: '/blog/$siteSlug/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSiteSlugPostSlugRoute = BlogSiteSlugPostSlugRouteImport.update({
  id: '/blog/$siteSlug/$postSlug',
  path: '/blog/$siteSlug/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingEnsureRoute = ApiOnboardingEnsureRouteImport.update({
  id: '/api/onboarding/ensure',
  path: '/api/onboarding/ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/posts': typeof ApiPostsRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/blog/$siteSlug/': typeof BlogSiteSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/posts': typeof ApiPostsRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/blog/$siteSlug': typeof BlogSiteSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/posts': typeof ApiPostsRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/blog/$siteSlug/': typeof BlogSiteSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/posts'
    | '/media-assets/$assetId'
    | '/api/auth/$'
    | '/api/onboarding/ensure'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/blog/$siteSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/posts'
    | '/media-assets/$assetId'
    | '/api/auth/$'
    | '/api/onboarding/ensure'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/blog/$siteSlug'
  id:
    | '__root__'
    | '/'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/posts'
    | '/media-assets/$assetId'
    | '/api/auth/$'
    | '/api/onboarding/ensure'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/blog/$siteSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPostsRoute: typeof ApiPostsRoute
  MediaAssetsAssetIdRoute: typeof MediaAssetsAssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOnboardingEnsureRoute: typeof ApiOnboardingEnsureRoute
  BlogSiteSlugPostSlugRoute: typeof BlogSiteSlugPostSlugRoute
  BlogSiteSlugLlmsDottxtRoute: typeof BlogSiteSlugLlmsDottxtRoute
  BlogSiteSlugIndexRoute: typeof BlogSiteSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-assets/$assetId': {
      id: '/media-assets/$assetId'
      path: '/media-assets/$assetId'
      fullPath: '/media-assets/$assetId'
      preLoaderRoute: typeof MediaAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$siteSlug/': {
      id: '/blog/$siteSlug/'
      path: '/blog/$siteSlug'
      fullPath: '/blog/$siteSlug/'
      preLoaderRoute: typeof BlogSiteSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$siteSlug/llms.txt': {
      id: '/blog/$siteSlug/llms.txt'
      path: '/blog/$siteSlug/llms.txt'
      fullPath: '/blog/$siteSlug/llms.txt'
      preLoaderRoute: typeof BlogSiteSlugLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$siteSlug/$postSlug': {
      id: '/blog/$siteSlug/$postSlug'
      path: '/blog/$siteSlug/$postSlug'
      fullPath: '/blog/$siteSlug/$postSlug'
      preLoaderRoute: typeof BlogSiteSlugPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/ensure': {
      id: '/api/onboarding/ensure'
      path: '/api/onboarding/ensure'
      fullPath: '/api/onboarding/ensure'
      preLoaderRoute: typeof ApiOnboardingEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPostsRoute: ApiPostsRoute,
  MediaAssetsAssetIdRoute: MediaAssetsAssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOnboardingEnsureRoute: ApiOnboardingEnsureRoute,
  BlogSiteSlugPostSlugRoute: BlogSiteSlugPostSlugRoute,
  BlogSiteSlugLlmsDottxtRoute: BlogSiteSlugLlmsDottxtRoute,
  BlogSiteSlugIndexRoute: BlogSiteSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
