/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as MediaAssetsAssetIdRouteImport } from './routes/media-assets/$assetId'
import { Route as AppSetupRouteImport } from './routes/app/setup'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppMediaRouteImport } from './routes/app/media'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as BlogSiteSlugIndexRouteImport } from './routes/blog/$siteSlug/index'
import { Route as AppPostsIndexRouteImport } from './routes/app/posts/index'
import { Route as BlogSiteSlugLlmsDottxtRouteImport } from './routes/blog/$siteSlug/llms[.]txt'
import { Route as BlogSiteSlugPostSlugRouteImport } from './routes/blog/$siteSlug/$postSlug'
import { Route as AppPostsNewRouteImport } from './routes/app/posts/new'
import { Route as ApiOnboardingEnsureRouteImport } from './routes/api/onboarding/ensure'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppPostsPostIdEditRouteImport } from './routes/app/posts/$postId/edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const MediaAssetsAssetIdRoute = MediaAssetsAssetIdRouteImport.update({
  id: '/media-assets/$assetId',
  path: '/media-assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSiteSlugIndexRoute = BlogSiteSlugIndexRouteImport.update({
  id: '/blog/$siteSlug/',
  path: '/blog/$siteSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const BlogSiteSlugLlmsDottxtRoute = BlogSiteSlugLlmsDottxtRouteImport.update({
  id: '/blog/$siteSlug/llms.txt',
  path: '/blog/$siteSlug/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSiteSlugPostSlugRoute = BlogSiteSlugPostSlugRouteImport.update({
  id: '/blog/$siteSlug/$postSlug',
  path: '/blog/$siteSlug/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsNewRoute = AppPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiOnboardingEnsureRoute = ApiOnboardingEnsureRouteImport.update({
  id: '/api/onboarding/ensure',
  path: '/api/onboarding/ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsPostIdEditRoute = AppPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/posts': typeof ApiPostsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/media': typeof AppMediaRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/app/posts/': typeof AppPostsIndexRoute
  '/blog/$siteSlug/': typeof BlogSiteSlugIndexRoute
  '/app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/posts': typeof ApiPostsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/media': typeof AppMediaRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/app/posts': typeof AppPostsIndexRoute
  '/blog/$siteSlug': typeof BlogSiteSlugIndexRoute
  '/app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/posts': typeof ApiPostsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/media': typeof AppMediaRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/app/posts/': typeof AppPostsIndexRoute
  '/blog/$siteSlug/': typeof BlogSiteSlugIndexRoute
  '/app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/posts'
    | '/app/activity'
    | '/app/media'
    | '/app/settings'
    | '/app/setup'
    | '/media-assets/$assetId'
    | '/app/'
    | '/api/auth/$'
    | '/api/onboarding/ensure'
    | '/app/posts/new'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/app/posts/'
    | '/blog/$siteSlug/'
    | '/app/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/posts'
    | '/app/activity'
    | '/app/media'
    | '/app/settings'
    | '/app/setup'
    | '/media-assets/$assetId'
    | '/app'
    | '/api/auth/$'
    | '/api/onboarding/ensure'
    | '/app/posts/new'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/app/posts'
    | '/blog/$siteSlug'
    | '/app/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/posts'
    | '/app/activity'
    | '/app/media'
    | '/app/settings'
    | '/app/setup'
    | '/media-assets/$assetId'
    | '/app/'
    | '/api/auth/$'
    | '/api/onboarding/ensure'
    | '/app/posts/new'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/app/posts/'
    | '/blog/$siteSlug/'
    | '/app/posts/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPostsRoute: typeof ApiPostsRoute
  MediaAssetsAssetIdRoute: typeof MediaAssetsAssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOnboardingEnsureRoute: typeof ApiOnboardingEnsureRoute
  BlogSiteSlugPostSlugRoute: typeof BlogSiteSlugPostSlugRoute
  BlogSiteSlugLlmsDottxtRoute: typeof BlogSiteSlugLlmsDottxtRoute
  BlogSiteSlugIndexRoute: typeof BlogSiteSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/media-assets/$assetId': {
      id: '/media-assets/$assetId'
      path: '/media-assets/$assetId'
      fullPath: '/media-assets/$assetId'
      preLoaderRoute: typeof MediaAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$siteSlug/': {
      id: '/blog/$siteSlug/'
      path: '/blog/$siteSlug'
      fullPath: '/blog/$siteSlug/'
      preLoaderRoute: typeof BlogSiteSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/posts/': {
      id: '/app/posts/'
      path: '/posts'
      fullPath: '/app/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/blog/$siteSlug/llms.txt': {
      id: '/blog/$siteSlug/llms.txt'
      path: '/blog/$siteSlug/llms.txt'
      fullPath: '/blog/$siteSlug/llms.txt'
      preLoaderRoute: typeof BlogSiteSlugLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$siteSlug/$postSlug': {
      id: '/blog/$siteSlug/$postSlug'
      path: '/blog/$siteSlug/$postSlug'
      fullPath: '/blog/$siteSlug/$postSlug'
      preLoaderRoute: typeof BlogSiteSlugPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/posts/new': {
      id: '/app/posts/new'
      path: '/posts/new'
      fullPath: '/app/posts/new'
      preLoaderRoute: typeof AppPostsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/onboarding/ensure': {
      id: '/api/onboarding/ensure'
      path: '/api/onboarding/ensure'
      fullPath: '/api/onboarding/ensure'
      preLoaderRoute: typeof ApiOnboardingEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/posts/$postId/edit': {
      id: '/app/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/app/posts/$postId/edit'
      preLoaderRoute: typeof AppPostsPostIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppMediaRoute: typeof AppMediaRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPostsNewRoute: typeof AppPostsNewRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
  AppPostsPostIdEditRoute: typeof AppPostsPostIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppMediaRoute: AppMediaRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
  AppPostsNewRoute: AppPostsNewRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
  AppPostsPostIdEditRoute: AppPostsPostIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  FeedDotxmlRoute: FeedDotxmlRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPostsRoute: ApiPostsRoute,
  MediaAssetsAssetIdRoute: MediaAssetsAssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOnboardingEnsureRoute: ApiOnboardingEnsureRoute,
  BlogSiteSlugPostSlugRoute: BlogSiteSlugPostSlugRoute,
  BlogSiteSlugLlmsDottxtRoute: BlogSiteSlugLlmsDottxtRoute,
  BlogSiteSlugIndexRoute: BlogSiteSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
