/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as PostSlugRouteImport } from './routes/$postSlug'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TagTagRouteImport } from './routes/tag/$tag'
import { Route as MediaAssetsAssetIdRouteImport } from './routes/media-assets/$assetId'
import { Route as DashboardSetupRouteImport } from './routes/dashboard_/setup'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMediaRouteImport } from './routes/dashboard/media'
import { Route as DashboardConnectRouteImport } from './routes/dashboard/connect'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardActivityRouteImport } from './routes/dashboard/activity'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiExportDotjsonRouteImport } from './routes/api/export[.]json'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardSettingsTokenCreatedRouteImport } from './routes/dashboard/settings/token-created'
import { Route as DashboardPostsNewRouteImport } from './routes/dashboard/posts/new'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar/webhook'
import { Route as ApiOnboardingEnsureRouteImport } from './routes/api/onboarding/ensure'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiMediaDeleteRouteImport } from './routes/api/media/delete'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardPostsPostIdEditRouteImport } from './routes/dashboard/posts/$postId/edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/$postSlug',
  path: '/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaAssetsAssetIdRoute = MediaAssetsAssetIdRouteImport.update({
  id: '/media-assets/$assetId',
  path: '/media-assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/dashboard_/setup',
  path: '/dashboard/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMediaRoute = DashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConnectRoute = DashboardConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportDotjsonRoute = ApiExportDotjsonRouteImport.update({
  id: '/api/export.json',
  path: '/api/export.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsTokenCreatedRoute =
  DashboardSettingsTokenCreatedRouteImport.update({
    id: '/token-created',
    path: '/token-created',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardPostsNewRoute = DashboardPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingEnsureRoute = ApiOnboardingEnsureRouteImport.update({
  id: '/api/onboarding/ensure',
  path: '/api/onboarding/ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaDeleteRoute = ApiMediaDeleteRouteImport.update({
  id: '/api/media/delete',
  path: '/api/media/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostsPostIdEditRoute =
  DashboardPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$postSlug': typeof PostSlugRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/export.json': typeof ApiExportDotjsonRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/connect': typeof DashboardConnectRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/settings/token-created': typeof DashboardSettingsTokenCreatedRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$postSlug': typeof PostSlugRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/export.json': typeof ApiExportDotjsonRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/connect': typeof DashboardConnectRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/settings/token-created': typeof DashboardSettingsTokenCreatedRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$postSlug': typeof PostSlugRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/export.json': typeof ApiExportDotjsonRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/connect': typeof DashboardConnectRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard_/setup': typeof DashboardSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/settings/token-created': typeof DashboardSettingsTokenCreatedRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$postSlug'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/export.json'
    | '/api/posts'
    | '/api/subscribe'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/connect'
    | '/dashboard/media'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/media-assets/$assetId'
    | '/tag/$tag'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/media/delete'
    | '/api/media/upload'
    | '/api/onboarding/ensure'
    | '/api/polar/webhook'
    | '/api/v1/$'
    | '/dashboard/posts/new'
    | '/dashboard/settings/token-created'
    | '/dashboard/posts/'
    | '/dashboard/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$postSlug'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/export.json'
    | '/api/posts'
    | '/api/subscribe'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/connect'
    | '/dashboard/media'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/media-assets/$assetId'
    | '/tag/$tag'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/media/delete'
    | '/api/media/upload'
    | '/api/onboarding/ensure'
    | '/api/polar/webhook'
    | '/api/v1/$'
    | '/dashboard/posts/new'
    | '/dashboard/settings/token-created'
    | '/dashboard/posts'
    | '/dashboard/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$postSlug'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/export.json'
    | '/api/posts'
    | '/api/subscribe'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/connect'
    | '/dashboard/media'
    | '/dashboard/settings'
    | '/dashboard_/setup'
    | '/media-assets/$assetId'
    | '/tag/$tag'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/media/delete'
    | '/api/media/upload'
    | '/api/onboarding/ensure'
    | '/api/polar/webhook'
    | '/api/v1/$'
    | '/dashboard/posts/new'
    | '/dashboard/settings/token-created'
    | '/dashboard/posts/'
    | '/dashboard/posts/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PostSlugRoute: typeof PostSlugRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiExportDotjsonRoute: typeof ApiExportDotjsonRoute
  ApiPostsRoute: typeof ApiPostsRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  MediaAssetsAssetIdRoute: typeof MediaAssetsAssetIdRoute
  TagTagRoute: typeof TagTagRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaDeleteRoute: typeof ApiMediaDeleteRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiOnboardingEnsureRoute: typeof ApiOnboardingEnsureRoute
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$postSlug': {
      id: '/$postSlug'
      path: '/$postSlug'
      fullPath: '/$postSlug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-assets/$assetId': {
      id: '/media-assets/$assetId'
      path: '/media-assets/$assetId'
      fullPath: '/media-assets/$assetId'
      preLoaderRoute: typeof MediaAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/setup': {
      id: '/dashboard_/setup'
      path: '/dashboard/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/media': {
      id: '/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof DashboardMediaRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/connect': {
      id: '/dashboard/connect'
      path: '/connect'
      fullPath: '/dashboard/connect'
      preLoaderRoute: typeof DashboardConnectRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export.json': {
      id: '/api/export.json'
      path: '/api/export.json'
      fullPath: '/api/export.json'
      preLoaderRoute: typeof ApiExportDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/token-created': {
      id: '/dashboard/settings/token-created'
      path: '/token-created'
      fullPath: '/dashboard/settings/token-created'
      preLoaderRoute: typeof DashboardSettingsTokenCreatedRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/posts/new': {
      id: '/dashboard/posts/new'
      path: '/posts/new'
      fullPath: '/dashboard/posts/new'
      preLoaderRoute: typeof DashboardPostsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/ensure': {
      id: '/api/onboarding/ensure'
      path: '/api/onboarding/ensure'
      fullPath: '/api/onboarding/ensure'
      preLoaderRoute: typeof ApiOnboardingEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/delete': {
      id: '/api/media/delete'
      path: '/api/media/delete'
      fullPath: '/api/media/delete'
      preLoaderRoute: typeof ApiMediaDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/posts/$postId/edit': {
      id: '/dashboard/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/dashboard/posts/$postId/edit'
      preLoaderRoute: typeof DashboardPostsPostIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsTokenCreatedRoute: typeof DashboardSettingsTokenCreatedRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsTokenCreatedRoute: DashboardSettingsTokenCreatedRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardConnectRoute: typeof DashboardConnectRoute
  DashboardMediaRoute: typeof DashboardMediaRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPostsNewRoute: typeof DashboardPostsNewRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardPostsPostIdEditRoute: typeof DashboardPostsPostIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardConnectRoute: DashboardConnectRoute,
  DashboardMediaRoute: DashboardMediaRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostsNewRoute: DashboardPostsNewRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardPostsPostIdEditRoute: DashboardPostsPostIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PostSlugRoute: PostSlugRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiExportDotjsonRoute: ApiExportDotjsonRoute,
  ApiPostsRoute: ApiPostsRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  MediaAssetsAssetIdRoute: MediaAssetsAssetIdRoute,
  TagTagRoute: TagTagRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaDeleteRoute: ApiMediaDeleteRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiOnboardingEnsureRoute: ApiOnboardingEnsureRoute,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
