/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as TagTagRouteImport } from './routes/tag/$tag'
import { Route as MediaAssetsAssetIdRouteImport } from './routes/media-assets/$assetId'
import { Route as AppSetupRouteImport } from './routes/app/setup'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppMediaRouteImport } from './routes/app/media'
import { Route as AppConnectRouteImport } from './routes/app/connect'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiPostsRouteImport } from './routes/api/posts'
import { Route as ApiExportDotjsonRouteImport } from './routes/api/export[.]json'
import { Route as BlogSiteSlugIndexRouteImport } from './routes/blog/$siteSlug/index'
import { Route as AppPostsIndexRouteImport } from './routes/app/posts/index'
import { Route as BlogSiteSlugLlmsDottxtRouteImport } from './routes/blog/$siteSlug/llms[.]txt'
import { Route as BlogSiteSlugPostSlugRouteImport } from './routes/blog/$siteSlug/$postSlug'
import { Route as AppSettingsTokenCreatedRouteImport } from './routes/app/settings/token-created'
import { Route as AppPostsNewRouteImport } from './routes/app/posts/new'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar/webhook'
import { Route as ApiOnboardingEnsureRouteImport } from './routes/api/onboarding/ensure'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiMediaDeleteRouteImport } from './routes/api/media/delete'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BlogSiteSlugTagTagRouteImport } from './routes/blog/$siteSlug/tag/$tag'
import { Route as AppPostsPostIdEditRouteImport } from './routes/app/posts/$postId/edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaAssetsAssetIdRoute = MediaAssetsAssetIdRouteImport.update({
  id: '/media-assets/$assetId',
  path: '/media-assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsRoute = ApiPostsRouteImport.update({
  id: '/api/posts',
  path: '/api/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportDotjsonRoute = ApiExportDotjsonRouteImport.update({
  id: '/api/export.json',
  path: '/api/export.json',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSiteSlugIndexRoute = BlogSiteSlugIndexRouteImport.update({
  id: '/blog/$siteSlug/',
  path: '/blog/$siteSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const BlogSiteSlugLlmsDottxtRoute = BlogSiteSlugLlmsDottxtRouteImport.update({
  id: '/blog/$siteSlug/llms.txt',
  path: '/blog/$siteSlug/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSiteSlugPostSlugRoute = BlogSiteSlugPostSlugRouteImport.update({
  id: '/blog/$siteSlug/$postSlug',
  path: '/blog/$siteSlug/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsTokenCreatedRoute = AppSettingsTokenCreatedRouteImport.update({
  id: '/token-created',
  path: '/token-created',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPostsNewRoute = AppPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingEnsureRoute = ApiOnboardingEnsureRouteImport.update({
  id: '/api/onboarding/ensure',
  path: '/api/onboarding/ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaDeleteRoute = ApiMediaDeleteRouteImport.update({
  id: '/api/media/delete',
  path: '/api/media/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSiteSlugTagTagRoute = BlogSiteSlugTagTagRouteImport.update({
  id: '/blog/$siteSlug/tag/$tag',
  path: '/blog/$siteSlug/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsPostIdEditRoute = AppPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/export.json': typeof ApiExportDotjsonRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/app/activity': typeof AppActivityRoute
  '/app/billing': typeof AppBillingRoute
  '/app/connect': typeof AppConnectRoute
  '/app/media': typeof AppMediaRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/setup': typeof AppSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/settings/token-created': typeof AppSettingsTokenCreatedRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/app/posts/': typeof AppPostsIndexRoute
  '/blog/$siteSlug/': typeof BlogSiteSlugIndexRoute
  '/app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/blog/$siteSlug/tag/$tag': typeof BlogSiteSlugTagTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/export.json': typeof ApiExportDotjsonRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/app/activity': typeof AppActivityRoute
  '/app/billing': typeof AppBillingRoute
  '/app/connect': typeof AppConnectRoute
  '/app/media': typeof AppMediaRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/setup': typeof AppSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/settings/token-created': typeof AppSettingsTokenCreatedRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/app/posts': typeof AppPostsIndexRoute
  '/blog/$siteSlug': typeof BlogSiteSlugIndexRoute
  '/app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/blog/$siteSlug/tag/$tag': typeof BlogSiteSlugTagTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/feed.xml': typeof FeedDotxmlRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/export.json': typeof ApiExportDotjsonRoute
  '/api/posts': typeof ApiPostsRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/app/activity': typeof AppActivityRoute
  '/app/billing': typeof AppBillingRoute
  '/app/connect': typeof AppConnectRoute
  '/app/media': typeof AppMediaRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/setup': typeof AppSetupRoute
  '/media-assets/$assetId': typeof MediaAssetsAssetIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/delete': typeof ApiMediaDeleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/onboarding/ensure': typeof ApiOnboardingEnsureRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/settings/token-created': typeof AppSettingsTokenCreatedRoute
  '/blog/$siteSlug/$postSlug': typeof BlogSiteSlugPostSlugRoute
  '/blog/$siteSlug/llms.txt': typeof BlogSiteSlugLlmsDottxtRoute
  '/app/posts/': typeof AppPostsIndexRoute
  '/blog/$siteSlug/': typeof BlogSiteSlugIndexRoute
  '/app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/blog/$siteSlug/tag/$tag': typeof BlogSiteSlugTagTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/export.json'
    | '/api/posts'
    | '/api/subscribe'
    | '/app/activity'
    | '/app/billing'
    | '/app/connect'
    | '/app/media'
    | '/app/settings'
    | '/app/setup'
    | '/media-assets/$assetId'
    | '/tag/$tag'
    | '/app/'
    | '/api/auth/$'
    | '/api/media/delete'
    | '/api/media/upload'
    | '/api/onboarding/ensure'
    | '/api/polar/webhook'
    | '/api/v1/$'
    | '/app/posts/new'
    | '/app/settings/token-created'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/app/posts/'
    | '/blog/$siteSlug/'
    | '/app/posts/$postId/edit'
    | '/blog/$siteSlug/tag/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/export.json'
    | '/api/posts'
    | '/api/subscribe'
    | '/app/activity'
    | '/app/billing'
    | '/app/connect'
    | '/app/media'
    | '/app/settings'
    | '/app/setup'
    | '/media-assets/$assetId'
    | '/tag/$tag'
    | '/app'
    | '/api/auth/$'
    | '/api/media/delete'
    | '/api/media/upload'
    | '/api/onboarding/ensure'
    | '/api/polar/webhook'
    | '/api/v1/$'
    | '/app/posts/new'
    | '/app/settings/token-created'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/app/posts'
    | '/blog/$siteSlug'
    | '/app/posts/$postId/edit'
    | '/blog/$siteSlug/tag/$tag'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/feed.xml'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/export.json'
    | '/api/posts'
    | '/api/subscribe'
    | '/app/activity'
    | '/app/billing'
    | '/app/connect'
    | '/app/media'
    | '/app/settings'
    | '/app/setup'
    | '/media-assets/$assetId'
    | '/tag/$tag'
    | '/app/'
    | '/api/auth/$'
    | '/api/media/delete'
    | '/api/media/upload'
    | '/api/onboarding/ensure'
    | '/api/polar/webhook'
    | '/api/v1/$'
    | '/app/posts/new'
    | '/app/settings/token-created'
    | '/blog/$siteSlug/$postSlug'
    | '/blog/$siteSlug/llms.txt'
    | '/app/posts/'
    | '/blog/$siteSlug/'
    | '/app/posts/$postId/edit'
    | '/blog/$siteSlug/tag/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiExportDotjsonRoute: typeof ApiExportDotjsonRoute
  ApiPostsRoute: typeof ApiPostsRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  MediaAssetsAssetIdRoute: typeof MediaAssetsAssetIdRoute
  TagTagRoute: typeof TagTagRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaDeleteRoute: typeof ApiMediaDeleteRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiOnboardingEnsureRoute: typeof ApiOnboardingEnsureRoute
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  BlogSiteSlugPostSlugRoute: typeof BlogSiteSlugPostSlugRoute
  BlogSiteSlugLlmsDottxtRoute: typeof BlogSiteSlugLlmsDottxtRoute
  BlogSiteSlugIndexRoute: typeof BlogSiteSlugIndexRoute
  BlogSiteSlugTagTagRoute: typeof BlogSiteSlugTagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-assets/$assetId': {
      id: '/media-assets/$assetId'
      path: '/media-assets/$assetId'
      fullPath: '/media-assets/$assetId'
      preLoaderRoute: typeof MediaAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts': {
      id: '/api/posts'
      path: '/api/posts'
      fullPath: '/api/posts'
      preLoaderRoute: typeof ApiPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export.json': {
      id: '/api/export.json'
      path: '/api/export.json'
      fullPath: '/api/export.json'
      preLoaderRoute: typeof ApiExportDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$siteSlug/': {
      id: '/blog/$siteSlug/'
      path: '/blog/$siteSlug'
      fullPath: '/blog/$siteSlug/'
      preLoaderRoute: typeof BlogSiteSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/posts/': {
      id: '/app/posts/'
      path: '/posts'
      fullPath: '/app/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/blog/$siteSlug/llms.txt': {
      id: '/blog/$siteSlug/llms.txt'
      path: '/blog/$siteSlug/llms.txt'
      fullPath: '/blog/$siteSlug/llms.txt'
      preLoaderRoute: typeof BlogSiteSlugLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$siteSlug/$postSlug': {
      id: '/blog/$siteSlug/$postSlug'
      path: '/blog/$siteSlug/$postSlug'
      fullPath: '/blog/$siteSlug/$postSlug'
      preLoaderRoute: typeof BlogSiteSlugPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/token-created': {
      id: '/app/settings/token-created'
      path: '/token-created'
      fullPath: '/app/settings/token-created'
      preLoaderRoute: typeof AppSettingsTokenCreatedRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/posts/new': {
      id: '/app/posts/new'
      path: '/posts/new'
      fullPath: '/app/posts/new'
      preLoaderRoute: typeof AppPostsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/ensure': {
      id: '/api/onboarding/ensure'
      path: '/api/onboarding/ensure'
      fullPath: '/api/onboarding/ensure'
      preLoaderRoute: typeof ApiOnboardingEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/delete': {
      id: '/api/media/delete'
      path: '/api/media/delete'
      fullPath: '/api/media/delete'
      preLoaderRoute: typeof ApiMediaDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$siteSlug/tag/$tag': {
      id: '/blog/$siteSlug/tag/$tag'
      path: '/blog/$siteSlug/tag/$tag'
      fullPath: '/blog/$siteSlug/tag/$tag'
      preLoaderRoute: typeof BlogSiteSlugTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/posts/$postId/edit': {
      id: '/app/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/app/posts/$postId/edit'
      preLoaderRoute: typeof AppPostsPostIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsTokenCreatedRoute: typeof AppSettingsTokenCreatedRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsTokenCreatedRoute: AppSettingsTokenCreatedRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppBillingRoute: typeof AppBillingRoute
  AppConnectRoute: typeof AppConnectRoute
  AppMediaRoute: typeof AppMediaRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPostsNewRoute: typeof AppPostsNewRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
  AppPostsPostIdEditRoute: typeof AppPostsPostIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppBillingRoute: AppBillingRoute,
  AppConnectRoute: AppConnectRoute,
  AppMediaRoute: AppMediaRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
  AppPostsNewRoute: AppPostsNewRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
  AppPostsPostIdEditRoute: AppPostsPostIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  FeedDotxmlRoute: FeedDotxmlRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiExportDotjsonRoute: ApiExportDotjsonRoute,
  ApiPostsRoute: ApiPostsRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  MediaAssetsAssetIdRoute: MediaAssetsAssetIdRoute,
  TagTagRoute: TagTagRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaDeleteRoute: ApiMediaDeleteRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiOnboardingEnsureRoute: ApiOnboardingEnsureRoute,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  BlogSiteSlugPostSlugRoute: BlogSiteSlugPostSlugRoute,
  BlogSiteSlugLlmsDottxtRoute: BlogSiteSlugLlmsDottxtRoute,
  BlogSiteSlugIndexRoute: BlogSiteSlugIndexRoute,
  BlogSiteSlugTagTagRoute: BlogSiteSlugTagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
