/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSetupRouteImport } from './routes/dashboard_/setup'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMediaRouteImport } from './routes/dashboard/media'
import { Route as DashboardConnectRouteImport } from './routes/dashboard/connect'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardActivityRouteImport } from './routes/dashboard/activity'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as DashboardSettingsTokenCreatedRouteImport } from './routes/dashboard/settings/token-created'
import { Route as DashboardPostsNewRouteImport } from './routes/dashboard/posts/new'
import { Route as DashboardPostsPostIdEditRouteImport } from './routes/dashboard/posts/$postId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/dashboard_/setup',
  path: '/dashboard/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMediaRoute = DashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConnectRoute = DashboardConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsTokenCreatedRoute =
  DashboardSettingsTokenCreatedRouteImport.update({
    id: '/token-created',
    path: '/token-created',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardPostsNewRoute = DashboardPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsPostIdEditRoute =
  DashboardPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/connect': typeof DashboardConnectRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/settings/token-created': typeof DashboardSettingsTokenCreatedRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/connect': typeof DashboardConnectRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/settings/token-created': typeof DashboardSettingsTokenCreatedRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/connect': typeof DashboardConnectRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard_/setup': typeof DashboardSetupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/posts/new': typeof DashboardPostsNewRoute
  '/dashboard/settings/token-created': typeof DashboardSettingsTokenCreatedRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/posts/$postId/edit': typeof DashboardPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/connect'
    | '/dashboard/media'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/dashboard/'
    | '/dashboard/posts/new'
    | '/dashboard/settings/token-created'
    | '/dashboard/posts/'
    | '/dashboard/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/connect'
    | '/dashboard/media'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/dashboard'
    | '/dashboard/posts/new'
    | '/dashboard/settings/token-created'
    | '/dashboard/posts'
    | '/dashboard/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/billing'
    | '/dashboard/connect'
    | '/dashboard/media'
    | '/dashboard/settings'
    | '/dashboard_/setup'
    | '/dashboard/'
    | '/dashboard/posts/new'
    | '/dashboard/settings/token-created'
    | '/dashboard/posts/'
    | '/dashboard/posts/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard_/setup': {
      id: '/dashboard_/setup'
      path: '/dashboard/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/media': {
      id: '/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof DashboardMediaRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/connect': {
      id: '/dashboard/connect'
      path: '/connect'
      fullPath: '/dashboard/connect'
      preLoaderRoute: typeof DashboardConnectRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/token-created': {
      id: '/dashboard/settings/token-created'
      path: '/token-created'
      fullPath: '/dashboard/settings/token-created'
      preLoaderRoute: typeof DashboardSettingsTokenCreatedRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/posts/new': {
      id: '/dashboard/posts/new'
      path: '/posts/new'
      fullPath: '/dashboard/posts/new'
      preLoaderRoute: typeof DashboardPostsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/$postId/edit': {
      id: '/dashboard/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/dashboard/posts/$postId/edit'
      preLoaderRoute: typeof DashboardPostsPostIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsTokenCreatedRoute: typeof DashboardSettingsTokenCreatedRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsTokenCreatedRoute: DashboardSettingsTokenCreatedRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardConnectRoute: typeof DashboardConnectRoute
  DashboardMediaRoute: typeof DashboardMediaRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPostsNewRoute: typeof DashboardPostsNewRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardPostsPostIdEditRoute: typeof DashboardPostsPostIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardConnectRoute: DashboardConnectRoute,
  DashboardMediaRoute: DashboardMediaRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostsNewRoute: DashboardPostsNewRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardPostsPostIdEditRoute: DashboardPostsPostIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  DashboardSetupRoute: DashboardSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
