/// <reference types="@cloudflare/vitest-pool-workers" />
/// <reference types="@cloudflare/vitest-pool-workers/types" />

import { describe, it, expect, beforeAll, inject } from "vitest";
import { env } from "cloudflare:workers";
import { applyD1Migrations } from "cloudflare:test";
import type { D1Migration } from "cloudflare:test";
import type { Actor } from "@vc/core";
import {
  loadPersonalization,
  updatePersonalizationForApp,
  type AppUserContext,
} from "@/server/onboarding";

declare module "vitest" {
  interface ProvidedContext {
    migrations: D1Migration[];
  }
}

const SITE_ID = "site-personalization";
const WORKSPACE_ID = "ws-personalization";
const T = 1_704_000_000;

function ownerApp(): AppUserContext {
  const actor: Actor = { type: "human", id: "owner-pz", name: "Owner", role: "owner" };
  return {
    user: { id: "owner-pz", name: "Owner", email: "owner@example.com" },
    siteId: SITE_ID,
    workspaceId: WORKSPACE_ID,
    actor,
  };
}

function editorApp(): AppUserContext {
  const actor: Actor = { type: "human", id: "editor-pz", name: "Editor", role: "editor" };
  return {
    user: { id: "editor-pz", name: "Editor", email: "editor@example.com" },
    siteId: SITE_ID,
    workspaceId: WORKSPACE_ID,
    actor,
  };
}

beforeAll(async () => {
  const migrations = inject("migrations") as D1Migration[];
  await applyD1Migrations(env.DB, migrations);
  await env.DB.prepare(
    "INSERT INTO workspaces (id, name, slug, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
  )
    .bind(WORKSPACE_ID, "PZ Workspace", "ws-personalization", T, T)
    .run();
  await env.DB.prepare(
    "INSERT INTO sites (id, workspace_id, name, slug, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
  )
    .bind(SITE_ID, WORKSPACE_ID, "PZ Site", SITE_ID, T, T)
    .run();
});

describe("site personalization", () => {
  it("defaults to an unanswered profile before Make it yours is completed", async () => {
    const profile = await loadPersonalization(ownerApp());
    expect(profile).toEqual({ agentPreference: null, voiceSeed: [], onboardingNote: null });
  });

  it("requires the owner role to save", async () => {
    const result = await updatePersonalizationForApp(editorApp(), {
      agentPreference: "codex",
    });
    expect(result).toEqual({ kind: "error", code: "owner_required" });
    const profile = await loadPersonalization(ownerApp());
    expect(profile.agentPreference).toBeNull();
  });

  it("saves agent preference, voice seed, and note with activity", async () => {
    const result = await updatePersonalizationForApp(ownerApp(), {
      agentPreference: "claude_code",
      voiceSeed: ["https://example.com/essays", "example.com/notes"],
      onboardingNote: "Docs generated by tools feel like templates.",
    });
    expect(result.kind).toBe("ok");
    const profile = await loadPersonalization(ownerApp());
    expect(profile.agentPreference).toBe("claude_code");
    expect(profile.voiceSeed).toEqual([
      "https://example.com/essays",
      "https://example.com/notes",
    ]);
    expect(profile.onboardingNote).toBe("Docs generated by tools feel like templates.");

    const activity = await env.DB.prepare(
      "SELECT action, summary FROM activity_events WHERE site_id = ? ORDER BY created_at DESC LIMIT 1",
    )
      .bind(SITE_ID)
      .first<{ action: string; summary: string }>();
    expect(activity?.action).toBe("site.updated");
    expect(activity?.summary).toBe("Personalized the onboarding guidance");
  });

  it("sanitizes the voice seed: dedupes, caps at three, drops invalid URLs", async () => {
    const result = await updatePersonalizationForApp(ownerApp(), {
      agentPreference: "not-an-agent",
      voiceSeed: [
        "https://example.com/a",
        "https://example.com/a",
        "javascript:alert(1)",
        "example.com/b",
        "example.com/c",
        "example.com/d",
        "not a url at all%%",
      ],
      onboardingNote: "   ",
    });
    expect(result.kind).toBe("ok");
    const profile = await loadPersonalization(ownerApp());
    expect(profile.agentPreference).toBeNull();
    expect(profile.voiceSeed).toEqual([
      "https://example.com/a",
      "https://example.com/b",
      "https://example.com/c",
    ]);
    expect(profile.onboardingNote).toBeNull();
  });
});
